garcon/activity.py
garcon/decider.py
garcon/task.py
tests/test_task.py

Some tasks may require more time than the default timeout. This update allows to set a timeout
on specific tasks.
Example:
from garcon import task
@task.timeout(3600)
def task_a(context):
pass

Add timeout on methods.

---

garcon/event.py

Some workflows can be generic enough to work with a set of parameters that can be provided
at the execution of the workflow.

Add input of the workflow as part of the context.

---

garcon/task.py
tests/test_task.py

Two new decorators have been added:
* `task.decorator`: which is a generic decorator for tasks. You can pass a timeout and
`enable_contextify`.
* `task.contextify`: which methods gets information from the context and send it to the
task.
Background:
The context is being passed to all tasks. Having the ability to know which task consume
what information makes it easier to see additional dependencies between tasks. For
instance:
```
activity = create(
name=activity_name,
tasks=SyncTasks(
send_email.fill(
user_email='context.user_email',
user_full_name='context.user.full_name')))
```
To get the `fill` method, you can either do:
```
from garcon import tasks
@tasks.contextify
def send_email(user_email):
pass
@tasks.decorate()
def send_email(user_email):
pass
```
Please note:
> 1. Using the …

Add decorators.

---

README.md
example/test_flow.py
garcon/activity.py
tests/test_activity.py

Just some changes in the naming. Passing `tasks=` does not really reflect the fact
that we are passing a runner. So instead, we will be using `run` (which is self explanatory)
@rantonmattei

Switch `tasks` with `run`.

---

garcon/task.py

When the activity is not present as a param in the task list, the
activity fails – it should instead succeed.
@rantonmattei

Fix: when activity is not present on the task.

---

garcon/task.py
tests/test_task.py

If the task sets the timeout and contextify, the timeout stays on the original method,
not the contextify wrapper. Calling `.fill` ends up removing the `timeout`. Sharing the `_garcon_`
dictionary between the two methods solves this issue.
@rantonmattei

Update the task decoration.

---

garcon/activity.py
garcon/decider.py
garcon/runner.py
garcon/task.py
tests/test_activity.py
tests/test_decider.py
tests/test_runner.py
tests/test_task.py

Heartbeat is set by default by AWS (to 600 seconds, which is
10 minutes. If an activity last longer than 10 minutes but
does not issue a heartbeat - SWF considers this activity has
failed.
The heartbeat mechanism works on our end at task level. We
gather all the different heartbeats (if one activity misses
the heartbeat, it is set to the SWF default.) – and figure
out which one is the longuest. We use this one as a
reference for our task.
Additional notes:
* Everytime an activity spawns a new task, the heartbeat is
triggered.
* Everytime an activity finishes a task, a heartbeat is
triggered (this is for the async task runner.)
@rantonmattei

Add heartbeat.

---

garcon/activity.py
garcon/decider.py
tests/test_activity.py

Those two timeouts are calculated based on the assumption that only one
worker per activity. So if the user has set the create of the activity
to be 10 minutes and a generator spawns 10 activities, the schedule to start
will be 100 minutes.
Schedule to close timeout is an addition of schedule to start and start to
close timeout.
@rantonmattei

Add the schedule_to_start and schedule_to_close timeouts.

---

garcon/activity.py
garcon/decider.py
garcon/runner.py
garcon/task.py
tests/test_activity.py
tests/test_runner.py
tests/test_task.py

Activity generators have been very useful: they allow to spawn n instances of
an activity based on values in the context. The same can be done for tasks (
which makes it very handy when you write the logic units of your activity.)
**Goal**:
The goal of the generators is to provide an wasy way to write a list of tasks
if transformations need to be done within the context. The generator should also
contribute to the calculation of the different timeout values.
An additional goal was to make sure it is backward compatible: the way flows
have been written until today will remain the same.
**Example**:
```python
@task.list
def create_client(context):
yield create_user.fill(
username='context.username',
email='context.email')
if context.get('context.credit_card'):
yield create_credit_card.fill( …
```

Introducing Task Lists

---

garcon/activity.py
garcon/decider.py
tests/test_activity.py

The issue:
> The instance context is only representing the generator context.
> If this context is passed to the task.list, this context will appear
> empty.
Fix:
> Provide the execution context gathered by the decider to fill the
> necessary information
@rantonmattei

Fix instance context.

---

garcon/activity.py
garcon/runner.py
tests/test_activity.py

SWF allows any activities to be written in any language (polyglot.)
Garcon for now was locking all the activities to be written in python,
this change allows activities to be external workers (written in any
language.)
@pkuong @rantonmattei

Add support for external

---

garcon/param.py
garcon/task.py
tests/test_param.py
tests/test_task.py

Not all the values that needs to be passed to the tasks are from the context, they could be values
that are part of the flow configuration, and values that should not need to be sent to AWS (for
instance: database credentials.)
This features allows to parametrize the fill. You can use: StaticParam or Param. Param is the
default behavior, and StaticParam is a value passed to the activity without sending it to SWF.
Note: this is not compatible with external activities, external activities can only consume
values that have been sent to SWF.
Retrocompatibility is ensured: all value strings are turned into Param.
Example:
```python
print_country_id.fill(
country_id=param.Param('generator.country_id'),
static=param.StaticParam('Hello World'))
```
@rantonmattei

Add Param.

---

garcon/activity.py
garcon/decider.py
garcon/event.py
tests/test_decider.py

Some flows are more complex than others. For instance: some activities can
be scheduled based on a condition in the context. Being able to (easily)
write the decider has a lot of advantages.
For this: in your flow, you need to define a decider method that takes a
`schedule` param. To call an activity, all you have to do is to call
`schedule`, provide an immutable id, the activity and a list (if necessary)
of requirements. Example:
```python
def decider(schedule):
activity_1 = schedule(
'activity_1', test_activity_1)
activity_2 = schedule(
'activity_2', test_activity_2, requires=[activity_1])
for i in range(3):
activity_3 = schedule(
'activity-3.{}'.format(i), test_activity_3, requires=[activity_2])
if activity_3.ready and activity_2.result.get('4') == 4:
last_activity = schedule( …
```

Add support for manual deciders.

---

garcon/activity.py
garcon/decider.py
garcon/event.py
tests/fixtures/flows/example.py
tests/test_activity.py
tests/test_decider.py

The exception handler can be provided directly to the decider by adding a method
named `on_exception(actor, exception)` and / or to the `create` method. It allows
to perform an action after an error has happened (for instance: log the error
in sentry).
@rantonmattei

Add Exception handlers.

---

garcon/activity.py
tests/test_activity.py

Adding execution context when task decorated is used to fix issue with GarconLogger being unable to [domain].[workflow_id].[run_id] when task decorated is used. 
@xethorn @rantonmattei

Add execution context to input when used

---

garcon/task.py

This will help custom runners get better info about the task functions such as \__name__, which currently is always 'wrapper'.

let wrapper from task.contextify look more like the wrapped function

---

.travis.yml
garcon/activity.py
tests/test_activity.py

The default behavior should be to send only what an activity requires
to run, instead of sending the full context. This was added in #64, so
handpicking those values will solve the problem.
@someboredkiddo @rantonmattei

Remove full context from input.

---

garcon/activity.py
tests/test_activity.py

@xethorn, Execution of a flow may fail in case context has item like {'key': []} or any with value that converts to False.

Filter only None values.

---

garcon/activity.py
tests/test_activity.py

hey @xethorn 
We noticed that occasionally AWS throttles during a worker/decider poll(), causing the thread running that worker for a particular activity to die.  Because there is no longer a worker for that activity, Workflows then get stuck when trying to execute that activity.
This initial PR adds a simple try | catch to avoid the daemon from dying. I'll make another after this to add some sort of sleep if the exception raised is related to throttling, as well as another one for the decider's poll() call.
see below for an example of the error message
```
2017-08-03 14:54:37,605 DEBG 'XXX-worker_00' stderr output:
Exception in thread Thread-7:
Traceback (most recent call last):
File "/usr/local/lib/python3.4/threading.py", line 920, in _bootstrap_inner
self.run()
File …
```

Add error catching for Activity polling

---

garcon/activity.py
garcon/utils.py
requirements.txt
setup.py
tests/test_activity.py
tests/test_utils.py

Add exponential backoff to deal with AWS SWF API throttles when polling
Note this is only required because boto2 does not implement exponential backoff on its own when making API calls to AWS. Upgrading to boto3 would resolve this.

Add exponential backoff for Activity poll

---

.travis.yml
README.rst
example/custom_decider/run.py
example/custom_decider/workflow.py
example/simple/run.py
example/simple/workflow.py
garcon/activity.py
garcon/decider.py
garcon/utils.py
requirements.txt
setup.py
tests/conftest.py
tests/fixtures/flows/example.py
tests/test_activity.py
tests/test_context.py
tests/test_decider.py
tests/test_runner.py
tests/test_utils.py
tox.ini

Boto3 has been out for some time now and boto2 will likely be
deprecated in months / years to come. Since most AWS users are
now on boto3, migrating Garcon to Boto3.
This upgrade introduces couple breaking changes:
* `Workflow` now needs a `client` (`boto3.client('aws', region_name='us-east-1')`)
to work. It enables workflows to run on specific AWS regions.
* `ActivityExecution` is now passed to the Runner instead of the
`Activity`. Similar to boto2 activities, you can perform operations
on the execution such as `complete`, `fail` and `heartbeat`.

Migrate from boto2 to boto3.

---

garcon/activity.py

This PR fixes error with boto3 S3 client during file transfer
```
RuntimeError: cannot schedule new futures after interpreter shutdown
```
All created threads have to be joined with starter threads. It will fix s3transfer methods in boto3.
Boto3 issues discussed here:
* https://github.com/boto/boto3/issues/3113
* https://github.com/boto/boto3/issues/3221#issuecomment-1169369661
* https://github.com/boto/s3transfer/issues/197
This issue is actual for python >=3.9
The root Cpython issue: https://github.com/python/cpython/issues/86813

Fix threading error leading to boto3 S3 failures
